# -*- coding: utf-8 -*-
"""Problem_solving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yc6qljgn1JFDbwQyBmMogUN-gihqyRlw
"""

import numpy as np
from scipy.spatial import cKDTree
import matplotlib.pyplot as plt


# SCELTA DEL PROFILO INIZIALE

PROFILE = "ring"        # disco di Lynden-Bell & Pringle (self-similar)
                       # anello sottile attorno a R_ring


# PARAMETRI COMUNI

Mstar   = 1.0          # massa stellare           [Msun]
Mdisc   = 0.1          # massa totale del disco   [Msun]
R_T     = 100.0        # raggio di norm. della T  [AU]
T100    = 20.0         # temperatura a R_T        [K]
q       = 0.23         # pendenza di T
mu      = 2.35         # peso molecolare medio
N       = 1000         # numero di particelle
seed    = 42

# parametri specifici del profilo LBP
Rin     = 50.0
Rout    = 600.0
Rc      = 150.0
gamma   = 1.0

# parametri specifici del profilo ad anello
R_ring  = 200.0        # centro dell'anello
DR_ring = 20.0         # semi-larghezza

G = 4.0 * np.pi**2
kB = 1.380649e-16; mp = 1.6726219e-24
AU = 1.495978707e13; YR = 3.15576e7
CMS_TO_AUYR = YR / AU


# CAMPI FISICI COMUNI

def sound_speed(R):
    T = T100 * (R / R_T)**(-q)
    cs_cgs = np.sqrt(kB * T / (mu * mp))
    return cs_cgs * CMS_TO_AUYR

def v_kepler(R):
    return np.sqrt(G * Mstar / R)


# PROFILO LBP

def surface_density_lbp(R):
    pref = Mdisc * (2.0 - gamma) / (2.0 * np.pi * Rc**2)
    return pref * (R / Rc)**(-gamma) * np.exp(-(R / Rc)**(2.0 - gamma))

def v_phi_lbp(R):
    cs2 = sound_speed(R)**2
    corr = cs2 * (1.0 + R / Rc + 2.0*q)
    v2 = v_kepler(R)**2 - corr
    if np.any(v2 <= 0):
        n_bad = np.sum(v2 <= 0)
        print(f"  ATTENZIONE: {n_bad} particelle con v_phi^2<=0; clip a 0.")
        v2 = np.clip(v2, 0.0, None)
    return np.sqrt(v2)

def sample_radii_lbp(n, rng):
    a = np.exp(-Rin / Rc)
    b = np.exp(-Rout / Rc)
    u = rng.uniform(0.0, 1.0, n)
    return -Rc * np.log(a - u * (a - b))

def Mdisc_eff_lbp():
    return Mdisc * (np.exp(-Rin / Rc) - np.exp(-Rout / Rc))


# PROFILO AD ANELLO

def surface_density_ring(R):
    Sigma0 = Mdisc / (np.pi * ((R_ring+DR_ring)**2 - (R_ring-DR_ring)**2))
    return np.where(np.abs(R - R_ring) < DR_ring, Sigma0, 0.0)

def v_phi_ring(R):
    return v_kepler(R)

def sample_radii_ring(n, rng):
    u = rng.uniform(0.0, 1.0, n)
    Rin2  = (R_ring - DR_ring)**2
    Rout2 = (R_ring + DR_ring)**2
    return np.sqrt(u * (Rout2 - Rin2) + Rin2)

def Mdisc_eff_ring():
    return Mdisc



if PROFILE == "lbp":
    sample_radii    = sample_radii_lbp
    surface_density = surface_density_lbp
    v_phi           = v_phi_lbp
    Mdisc_eff       = Mdisc_eff_lbp
    R_inner_plot, R_outer_plot = Rin, Rout
elif PROFILE == "ring":
    sample_radii    = sample_radii_ring
    surface_density = surface_density_ring
    v_phi           = v_phi_ring
    Mdisc_eff       = Mdisc_eff_ring
    R_inner_plot, R_outer_plot = R_ring - 2*DR_ring, R_ring + 2*DR_ring
else:
    raise ValueError(f"PROFILE='{PROFILE}' non riconosciuto. Usa 'lbp' o 'ring'.")


# COSTRUZIONE DELLE CONDIZIONI INIZIALI

def build_ic():
    rng = np.random.default_rng(seed)

    R   = sample_radii(N, rng)
    phi = rng.uniform(0.0, 2.0*np.pi, N)
    x   = R * np.cos(phi)
    y   = R * np.sin(phi)

    Meff = Mdisc_eff()
    m = np.full(N, Meff / N)

    vphi = v_phi(R)
    vx = -vphi * np.sin(phi)
    vy =  vphi * np.cos(phi)

    print(f"Profilo: {PROFILE.upper()}")
    print(f"  N = {N},  massa effettiva = {Meff:.4f} Msun  "
          f"(massa/particella = {m[0]:.3e})")

    pts = np.column_stack([x, y])
    tree = cKDTree(pts)
    d, _ = tree.query(pts, k=2)
    h_suggerita = 1.2 * np.median(d[:,1])
    print(f"  Distanza mediana al primo vicino = {np.median(d[:,1]):.2f} AU")
    print(f"  -> h iniziale suggerito = {h_suggerita:.2f} AU")

    return dict(x=x, y=y, vx=vx, vy=vy, m=m, R=R, phi=phi, vphi=vphi,
                h=h_suggerita)


# DIAGNOSTICA

def plot_diagnostics(ic, fname="disc_ic_diagnostics.png"):
    x, y, R, vphi, m = ic['x'], ic['y'], ic['R'], ic['vphi'], ic['m']
    fig, ax = plt.subplots(1, 3, figsize=(16, 4.8))

    ax[0].scatter(x, y, s=3, c=R, cmap='viridis', alpha=0.7)
    ax[0].set_aspect('equal')
    ax[0].set_xlabel('x [AU]'); ax[0].set_ylabel('y [AU]')
    ax[0].set_title(f'IC face-on ({PROFILE})')

    if PROFILE == "lbp":
        bins = np.logspace(np.log10(R_inner_plot), np.log10(R_outer_plot), 30)
    else:
        bins = np.linspace(R_inner_plot, R_outer_plot, 30)
    counts, edges = np.histogram(R, bins=bins)
    area  = np.pi*(edges[1:]**2 - edges[:-1]**2)
    Sigma_meas = counts * m[0] / area
    Rmid  = 0.5*(edges[1:] + edges[:-1])
    Rfine = np.linspace(R_inner_plot, R_outer_plot, 200)

    if PROFILE == "lbp":
        ax[1].loglog(Rmid, Sigma_meas, 'o', ms=4, label='misurata')
        ax[1].loglog(Rfine, surface_density(Rfine), '-', label='analitica')
    else:
        ax[1].plot(Rmid, Sigma_meas, 'o', ms=4, label='misurata')
        ax[1].plot(Rfine, surface_density(Rfine), '-', label='analitica (box)')
    ax[1].set_xlabel('R [AU]'); ax[1].set_ylabel(r'$\Sigma$ [Msun/AU$^2$]')
    ax[1].set_title('Densita\' superficiale'); ax[1].legend()

    order = np.argsort(R)
    ax[2].plot(R[order], vphi[order], '.', ms=4, alpha=0.4, color='red',
               label=r'$v_\phi$ particelle')
    ax[2].plot(Rfine, v_kepler(Rfine), '--', label=r'$v_K$ (kepleriana)')
    if PROFILE == "lbp":
        ax[2].plot(Rfine, v_phi(Rfine), '-', lw=2, label=r'$v_\phi$ con pressione')
    ax[2].set_xlabel('R [AU]'); ax[2].set_ylabel('v [AU/yr]')
    ax[2].set_title('Curva di rotazione'); ax[2].legend()

    fig.tight_layout()
    fig.savefig(fname, dpi=110, bbox_inches='tight')
    print(f"  Grafici salvati in {fname}")


# MAIN

if __name__ == "__main__":
    ic = build_ic()
    plot_diagnostics(ic)
    np.savez("disc_ic.npz",
             x=ic['x'], y=ic['y'], vx=ic['vx'], vy=ic['vy'], m=ic['m'],
             h=ic['h'], Mstar=Mstar, G=G,
             Rc=Rc, R0=R_T, T100=T100, q=q, mu=mu)
    print("  Stato iniziale salvato in disc_ic.npz")

plt.show()

import numpy as np
from scipy.spatial import cKDTree
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import time
from numba import njit, prange


DIM = 2


# Carica lo stato iniziale dal file

data = np.load("disc_ic.npz")
N = len(data['x'])

pos = np.zeros((N, DIM))
vel = np.zeros((N, DIM))
pos[:,0] = data['x']; pos[:,1] = data['y']
vel[:,0] = data['vx']; vel[:,1] = data['vy']
if DIM == 3:
    pos[:,2] = data['z']; vel[:,2] = data['vz']

m = data['m'].copy()
h = np.full(N, float(data['h']))

Mstar = float(data['Mstar']);  G  = float(data['G'])
Rc    = float(data['Rc']);     R0 = float(data['R0'])
T100  = float(data['T100']);   q  = float(data['q']);  mu = float(data['mu'])


print(f"IC caricate (DIM={DIM}): N = {N}, massa totale = {m.sum():.4f} Msun")


# Costanti

kB = 1.380649e-16; mp_cgs = 1.6726219e-24
AU = 1.495978707e13; YR = 3.15576e7
CMS_TO_AUYR = YR / AU

ALPHA_AV = 1.0
BETA_AV  = 2.0
EPS_AV   = 0.01

ETA = 1.2
H_MIN, H_MAX = 0.5, 200.0


# Kernel cubic spline jit-compilato

@njit(inline='always', fastmath=True)
def W_value(r, h, dim):
    if h <= 0.0: return 0.0
    q = r / h
    if q < 1.0:
        f = 1.0 - 1.5*q*q + 0.75*q*q*q
    elif q < 2.0:
        f = 0.25*(2.0 - q)**3
    else:
        return 0.0
    sigma = 10.0/(7.0*np.pi) if dim == 2 else 1.0/np.pi
    return sigma * f / (h**dim)

@njit(inline='always', fastmath=True)
def dW_value(r, h, dim):
    if h <= 0.0 or r <= 0.0: return 0.0
    q = r / h
    if q < 1.0:
        f = -3.0*q + 2.25*q*q
    elif q < 2.0:
        f = -0.75*(2.0 - q)**2
    else:
        return 0.0
    sigma = 10.0/(7.0*np.pi) if dim == 2 else 1.0/np.pi
    return sigma * f / (h**(dim+1))


# Sound speed

def sound_speed(R):
    T = T100 * (R / R0)**(-q)
    cs_cgs = np.sqrt(kB * T / (mu * mp_cgs))
    return cs_cgs * CMS_TO_AUYR


# Pair-list piatta e simmetrizzata

def build_pairs(pos, h):
    """Coppie (i,j) entro 2*max(h_i,h_j), simmetrizzate (vale Newton 3)."""
    tree = cKDTree(pos)
    neigh = tree.query_ball_point(pos, r=2.0*h)
    counts = np.fromiter((len(n) for n in neigh), dtype=np.int64, count=len(neigh))
    M = counts.sum()
    pair_i = np.empty(M, dtype=np.int64)
    pair_j = np.empty(M, dtype=np.int64)
    k = 0
    for i, lst in enumerate(neigh):
        L = len(lst)
        if L:
            pair_i[k:k+L] = i
            pair_j[k:k+L] = lst
            k += L
    Nmax = pos.shape[0]
    code1 = pair_i * Nmax + pair_j
    code2 = pair_j * Nmax + pair_i
    code_union = np.unique(np.concatenate([code1, code2]))
    return code_union // Nmax, code_union % Nmax


# Densita'

@njit(parallel=True, fastmath=True)
def density_sum(pos, m, h, pair_i, pair_j, dim):
    N = pos.shape[0]
    rho = np.zeros(N)
    for k in prange(pair_i.size):
        i = pair_i[k]; j = pair_j[k]
        s = 0.0
        for d in range(dim):
            dx = pos[i,d] - pos[j,d]
            s += dx*dx
        r = np.sqrt(s)
        if r < 2.0*h[i]:
            rho[i] += m[j] * W_value(r, h[i], dim)
    return rho

@njit(parallel=True, fastmath=True)
def count_neighbours(pos, h, pair_i, pair_j, dim):
    """Numero di vicini effettivi (entro 2 h_i) per ogni particella."""
    N = pos.shape[0]
    nn = np.zeros(N, dtype=np.int64)
    for k in prange(pair_i.size):
        i = pair_i[k]; j = pair_j[k]
        s = 0.0
        for d in range(dim):
            dx = pos[i,d] - pos[j,d]
            s += dx*dx
        r = np.sqrt(s)
        if r < 2.0*h[i]:
            nn[i] += 1
    return nn

def compute_density(pos, m, h, n_iter=4):
    rho = np.zeros(pos.shape[0])
    for it in range(n_iter):
        pair_i, pair_j = build_pairs(pos, h)
        rho = density_sum(pos, m, h, pair_i, pair_j, DIM)
        h_new = ETA * np.power(m / np.maximum(rho, 1e-30), 1.0/DIM)
        h_new = np.clip(h_new, H_MIN, H_MAX)
        h = 0.5*(h + h_new)
    return rho, h, pair_i, pair_j


# Accelerazione

@njit(parallel=True, fastmath=True)
def accel_pressure_viscosity(pos, vel, m, rho, h, cs, P,
                              pair_i, pair_j, dim,
                              alpha_av, beta_av, eps_av):
    N = pos.shape[0]
    acc = np.zeros((N, dim))
    visc_max_per_pair = np.zeros(pair_i.size)

    for k in prange(pair_i.size):
        i = pair_i[k]; j = pair_j[k]
        if i == j:
            continue
        rij = np.empty(dim)
        s = 0.0
        for d in range(dim):
            rij[d] = pos[i,d] - pos[j,d]
            s += rij[d]*rij[d]
        r = np.sqrt(s)
        if r <= 0.0:
            continue
        hij = 0.5*(h[i] + h[j])
        if r >= 2.0*hij:
            continue
        dWdr = dW_value(r, hij, dim)
        vdotr = 0.0
        for d in range(dim):
            vdotr += (vel[i,d] - vel[j,d]) * rij[d]
        Pi = 0.0
        if vdotr < 0.0:
            mu_ij = hij * vdotr / (r*r + eps_av * hij*hij)
            cs_avg  = 0.5*(cs[i] + cs[j])
            rho_avg = 0.5*(rho[i] + rho[j])
            Pi = (-alpha_av * cs_avg * mu_ij + beta_av * mu_ij*mu_ij) / rho_avg
            visc_max_per_pair[k] = abs(mu_ij)
        coef = P[i]/(rho[i]*rho[i]) + P[j]/(rho[j]*rho[j]) + Pi
        fac  = -m[j] * coef * dWdr / r
        for d in range(dim):
            acc[i,d] += fac * rij[d]
    visc_max = visc_max_per_pair.max() if visc_max_per_pair.size > 0 else 0.0
    return acc, visc_max

def compute_acceleration(pos, vel, m, rho, h, cs, cs2, pair_i, pair_j):
    P = rho * cs2
    acc, visc_max = accel_pressure_viscosity(
        pos, vel, m, rho, h, cs, P,
        pair_i, pair_j, DIM,
        ALPHA_AV, BETA_AV, EPS_AV
    )
    R2 = np.sum(pos*pos, axis=1)
    R3 = R2 * np.sqrt(R2)
    for d in range(DIM):
        acc[:,d] -= G * Mstar * pos[:,d] / R3
    return acc, visc_max


# Timestep, sink, diagnostica

C_CFL = 0.3; C_ACC = 0.25; C_VISC = 0.25
def choose_dt(h, cs, acc, visc_max):
    dt_cfl = C_CFL * np.min(h / cs)
    a = np.sqrt(np.sum(acc*acc, axis=1))
    dt_acc = C_ACC * np.min(np.sqrt(h / np.maximum(a, 1e-30)))
    signal = (1.0 + 1.5*ALPHA_AV) * cs.max() + 1.5*BETA_AV * visc_max
    dt_visc = C_VISC * h.min() / max(signal, 1e-30)
    return min(dt_cfl, dt_acc, dt_visc)

R_SINK = 30.0
def apply_sink(pos, vel, m, h):
    R2 = np.sum(pos*pos, axis=1)
    keep = R2 > R_SINK**2
    return pos[keep], vel[keep], m[keep], h[keep], np.sum(~keep)

def disc_diagnostics(pos, vel, m):
    R = np.sqrt(np.sum(pos*pos, axis=1))
    cs2 = sound_speed(R)**2
    Ekin  = 0.5 * np.sum(m * np.sum(vel*vel, axis=1))
    Egrav = -np.sum(G * Mstar * m / R)
    Etherm = np.sum(m * cs2)
    Lz = np.sum(m * (pos[:,0]*vel[:,1] - pos[:,1]*vel[:,0]))
    return dict(Ekin=Ekin, Egrav=Egrav, Etherm=Etherm,
                Etot=Ekin+Egrav+Etherm, Lz=Lz, Mtot=np.sum(m))


# Loop temporale

T_END     = 5000.0
SNAP_EVERY = 50.0
PRINT_EVERY_STEP = 100

print(f"Viscosita': alpha={ALPHA_AV}, beta={BETA_AV}")
print("Step  t [yr]   dt [yr]   N    <rho>          <h> [AU]")

R  = np.sqrt(np.sum(pos*pos, axis=1)); cs = sound_speed(R); cs2 = cs*cs
rho, h, pair_i, pair_j = compute_density(pos, m, h)
acc, visc_max = compute_acceleration(pos, vel, m, rho, h, cs, cs2, pair_i, pair_j)

snapshots = []
diag_t = []; diag_data = []
n_neigh_init = count_neighbours(pos, h, pair_i, pair_j, DIM)
snapshots.append(dict(t=0.0, pos=pos.copy(), vel=vel.copy(),
                      rho=rho.copy(), h=h.copy(), n_neigh=n_neigh_init.copy()))
diag_t.append(0.0); diag_data.append(disc_diagnostics(pos, vel, m))

t = 0.0; step = 0; t_next_snap = SNAP_EVERY
t0 = time.time()
while t < T_END:
    dt = choose_dt(h, cs, acc, visc_max)
    if t + dt > T_END: dt = T_END - t

    vel += 0.5*dt*acc                              # primo kick
    pos += dt*vel                                  # drift
    pos, vel, m, h, n_lost = apply_sink(pos, vel, m, h)

    R = np.sqrt(np.sum(pos*pos, axis=1)); cs = sound_speed(R); cs2 = cs*cs
    rho, h, pair_i, pair_j = compute_density(pos, m, h)
    acc, visc_max = compute_acceleration(pos, vel, m, rho, h, cs, cs2, pair_i, pair_j)
    vel += 0.5*dt*acc                              # secondo kick

    t += dt; step += 1
    if step % PRINT_EVERY_STEP == 0 or step == 1:
        print(f"{step:4d}  {t:7.2f}  {dt:7.4f}  {len(m):4d}   "
              f"{rho.mean():.3e}    {h.mean():6.2f}")

    if t >= t_next_snap - 1e-9:
        nn = count_neighbours(pos, h, pair_i, pair_j, DIM)
        snapshots.append(dict(t=t, pos=pos.copy(), vel=vel.copy(),
                              rho=rho.copy(), h=h.copy(), n_neigh=nn))
        diag_t.append(t); diag_data.append(disc_diagnostics(pos, vel, m))
        t_next_snap += SNAP_EVERY

elapsed = time.time() - t0
print(f"\nFatto.  {step} passi in {elapsed:.1f} s ({elapsed/step*1000:.1f} ms/step).")
print(f"Snapshot salvati: {len(snapshots)}.")


# DIAGNOSTICA DI DENSITA' a vari tempi

print("\nGenero plot diagnostico di densita'...")

n_show = 4
idx_show = np.linspace(0, len(snapshots)-1, n_show, dtype=int)
selected = [snapshots[i] for i in idx_show]
colors = plt.cm.viridis(np.linspace(0, 0.85, n_show))

R_all_final = np.sqrt(np.sum(selected[-1]['pos']*selected[-1]['pos'], axis=1))
R_min = max(R_SINK, R_all_final.min())
R_max = R_all_final.max() * 1.02
bins = np.logspace(np.log10(R_min), np.log10(R_max), 30)
Rmid = 0.5*(bins[1:] + bins[:-1])

# profilo LBP di riferimento normalizzato in modo consistente con la IC:
# la normalizzazione impone la stessa massa dei dati a t=0 nel range [R_min, R_max].
GAMMA_LBP = 1.0
m0 = m.mean()                                   # massa per particella (costante)
_trapz = getattr(np, "trapezoid", np.trapz)     # compatibilita' numpy 1.x / 2.x

def lbp_shape(R, Rc_local, gamma=GAMMA_LBP):
    return (R/Rc_local)**(-gamma) * np.exp(-(R/Rc_local)**(2.0-gamma))

R_init = np.sqrt(np.sum(snapshots[0]['pos']*snapshots[0]['pos'], axis=1))
M_ref  = m0 * np.count_nonzero((R_init >= R_min) & (R_init <= R_max))
_Rg    = np.logspace(np.log10(R_min), np.log10(R_max), 4000)
C_lbp  = M_ref / _trapz(lbp_shape(_Rg, Rc) * 2.0*np.pi*_Rg, _Rg)

def Sigma_LBP_ref(R):
    return C_lbp * lbp_shape(R, Rc)

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# (1) Sigma(R) a vari tempi
ax1 = axes[0,0]
for s, c in zip(selected, colors):
    Rs = np.sqrt(np.sum(s['pos']*s['pos'], axis=1))
    counts, _ = np.histogram(Rs, bins=bins)
    area = np.pi*(bins[1:]**2 - bins[:-1]**2)
    Sig = counts * m0 / area
    ax1.loglog(Rmid, Sig, 'o-', ms=4, color=c, lw=1.2,
               label=f"t = {s['t']:.0f} yr")
Rfine = np.logspace(np.log10(R_min), np.log10(R_max), 200)
ax1.loglog(Rfine, Sigma_LBP_ref(Rfine),
           'k--', lw=2, alpha=0.7,
           label='LBP analitica\n(stessa M nel range, Rc)')
ax1.set_xlabel('R [AU]'); ax1.set_ylabel(r'$\Sigma$  [Msun/AU$^2$]')
ax1.set_title('Densita\' superficiale a vari tempi')
ax1.legend(fontsize=9); ax1.grid(alpha=0.3, which='both')

# (2) rho_i scatter al tempo finale
ax2 = axes[0,1]
s_last = selected[-1]
R_last = np.sqrt(np.sum(s_last['pos']*s_last['pos'], axis=1))
ax2.scatter(R_last, s_last['rho'], s=4, alpha=0.5, c=R_last, cmap='viridis')
ax2.set_xlabel('R [AU]'); ax2.set_ylabel(r'$\rho_{\rm SPH}$  [Msun/AU$^2$]')
ax2.set_yscale('log'); ax2.set_xscale('log')
ax2.set_title(f"Densita' SPH per particella a t={s_last['t']:.0f} yr\n"
              )
ax2.grid(alpha=0.3, which='both')

# (3) h(R) a vari tempi
ax3 = axes[1,0]
for s, c in zip(selected, colors):
    Rs = np.sqrt(np.sum(s['pos']*s['pos'], axis=1))
    h_mean = np.zeros(len(Rmid))
    for k in range(len(Rmid)):
        m_bin = (Rs >= bins[k]) & (Rs < bins[k+1])
        h_mean[k] = np.mean(s['h'][m_bin]) if m_bin.any() else np.nan
    ax3.loglog(Rmid, h_mean, 'o-', ms=4, color=c, lw=1.2,
               label=f"t = {s['t']:.0f} yr")
# <<< RIMOSSA la tratteggiata  eta*sqrt(m/Sigma) attesa
ax3.set_xlabel('R [AU]'); ax3.set_ylabel(r'$\langle h \rangle$  [AU]')
ax3.set_title('Smoothing length media per bin radiale')
ax3.legend(fontsize=9); ax3.grid(alpha=0.3, which='both')

# (4) numero vicini per R
ax4 = axes[1,1]
for s, c in zip(selected, colors):
    Rs = np.sqrt(np.sum(s['pos']*s['pos'], axis=1))
    nmean = np.zeros(len(Rmid))
    for k in range(len(Rmid)):
        m_bin = (Rs >= bins[k]) & (Rs < bins[k+1])
        nmean[k] = np.mean(s['n_neigh'][m_bin]) if m_bin.any() else np.nan
    ax4.semilogx(Rmid, nmean, 'o-', ms=4, color=c, lw=1.2,
                 label=f"t = {s['t']:.0f} yr")
# <<< RIMOSSA la linea orizzontale  target {DIM}D
ax4.set_xlabel('R [AU]'); ax4.set_ylabel(r'$\langle N_{\rm neigh}\rangle$')
ax4.set_title("Numero di vicini per particella (per bin R)")
ax4.legend(fontsize=9); ax4.grid(alpha=0.3, which='both')

fig.tight_layout()
fig.savefig("sph_density_diagnostics.png", dpi=110, bbox_inches='tight')
plt.show()
print("Salvato sph_density_diagnostics.png")


# Diagnostica energia/momento angolare

diag_t = np.array(diag_t)
Etot   = np.array([d['Etot']   for d in diag_data])
Lz     = np.array([d['Lz']     for d in diag_data])
Mtot   = np.array([d['Mtot']   for d in diag_data])
Ekin   = np.array([d['Ekin']   for d in diag_data])
Egrav  = np.array([d['Egrav']  for d in diag_data])
Etherm = np.array([d['Etherm'] for d in diag_data])
Etot_spec = Etot / Mtot; Lz_spec = Lz / Mtot

fig, axes = plt.subplots(2, 2, figsize=(13, 8))
axes[0,0].plot(diag_t, Ekin, label='E cinetica')
axes[0,0].plot(diag_t, Egrav, label='E gravitazionale')
axes[0,0].plot(diag_t, Etherm, label='E termica')
axes[0,0].plot(diag_t, Etot, 'k-', lw=2, label='E totale')
axes[0,0].set_xlabel('t [yr]'); axes[0,0].set_ylabel('E')
axes[0,0].set_title('Energia totale (componenti)')
axes[0,0].legend(); axes[0,0].grid(alpha=0.3)

axes[0,1].plot(diag_t, Etot_spec/Etot_spec[0] - 1, 'k-')
axes[0,1].axhline(0, color='gray', ls=':', lw=0.7)
axes[0,1].set_xlabel('t [yr]'); axes[0,1].set_ylabel(r'$\Delta E_{\rm spec}/E_{\rm spec}(0)$')
axes[0,1].set_title('Deriva di energia specifica'); axes[0,1].grid(alpha=0.3)

axes[1,0].plot(diag_t, Lz, 'b-', label='L_z totale')
axes[1,0].plot(diag_t, Mtot * Lz_spec[0], 'b--', alpha=0.5,
               label='atteso solo per perdita di massa')
axes[1,0].set_xlabel('t [yr]'); axes[1,0].set_ylabel(r'$L_z$')
axes[1,0].set_title('Momento angolare totale'); axes[1,0].legend(); axes[1,0].grid(alpha=0.3)

axes[1,1].plot(diag_t, Lz_spec/Lz_spec[0] - 1, 'b-')
axes[1,1].axhline(0, color='gray', ls=':', lw=0.7)
axes[1,1].set_xlabel('t [yr]'); axes[1,1].set_ylabel(r'$\Delta L_{z,\rm spec}/L_{z,\rm spec}(0)$')
axes[1,1].set_title('Deriva di momento angolare specifico'); axes[1,1].grid(alpha=0.3)
fig.tight_layout()
fig.savefig("sph_energy_angmom.png", dpi=110, bbox_inches='tight')
plt.show()
print("Salvato sph_energy_angmom.png")

print(f"\nDeriva relativa finale:")
print(f"  E_spec:  {(Etot_spec[-1]/Etot_spec[0] - 1):+.3e}")
print(f"  L_spec:  {(Lz_spec[-1]/Lz_spec[0]   - 1):+.3e}")
print(f"  Massa persa al sink: {(1 - Mtot[-1]/Mtot[0])*100:.2f}%")


# Animazione

print("\nGenero animazione...")
all_R = np.concatenate([np.sqrt(np.sum(s['pos']*s['pos'], axis=1)) for s in snapshots])
LIM = 1.1 * np.max(all_R)
fig_a, ax_a = plt.subplots(figsize=(7.5, 7.0))
ax_a.set_xlim(-LIM, LIM); ax_a.set_ylim(-LIM, LIM); ax_a.set_aspect('equal')
ax_a.set_xlabel('x [AU]'); ax_a.set_ylabel('y [AU]')

def color_from_rho(rho_): return np.log10(np.maximum(rho_, 1e-12))
all_logrho = np.concatenate([color_from_rho(s['rho']) for s in snapshots])
vmin, vmax = np.percentile(all_logrho, [2, 98])

scat = ax_a.scatter(snapshots[0]['pos'][:,0], snapshots[0]['pos'][:,1],
                    c=color_from_rho(snapshots[0]['rho']),
                    s=4, cmap='viridis', vmin=vmin, vmax=vmax)
cbar = plt.colorbar(scat, ax=ax_a, fraction=0.046)
cbar.set_label(r'$\log_{10}\rho$')
title = ax_a.set_title(f"t = {snapshots[0]['t']:.0f} yr,  N = {len(snapshots[0]['pos'])}")

def update(frame):
    s = snapshots[frame]
    scat.set_offsets(s['pos'][:,:2])
    scat.set_array(color_from_rho(s['rho']))
    title.set_text(f"t = {s['t']:.0f} yr,  N = {len(s['pos'])}")
    return scat, title

max_frames = 120
stride = max(1, len(snapshots)//max_frames)
frames = list(range(0, len(snapshots), stride))
if frames[-1] != len(snapshots)-1: frames.append(len(snapshots)-1)
anim = animation.FuncAnimation(fig_a, update, frames=frames, interval=80, blit=False)
anim.save("sph_disc_evolution.gif", writer=animation.PillowWriter(fps=12))
plt.close(fig_a)
print(f"Animazione salvata ({len(frames)} frame).")

